- hosts: 172.17.0.3
  become: no
  handlers:
    - name: Restart Apache2 on change
      service:
        name: httpd
        state: restarted
  tasks:
    - name: (Task 1) Install the Apache web server
      yum:
        name: httpd
        state: present
    - name: (Tash 2) Add the port in the /etc/apache2/ports.conf file to "Listen 8081"
      lineinfile:
        path: /etc/apache2/ports.conf
        insertafter: 'Listen 80'
        line: 'Listen 8081'
        state: present
    - name: (Task 3) Add the port to the /etc/apache/sites-enabled/000-default.conf
      lineinfile:
        path: /etc/apache2/sites-enabled/000-default.conf
        regexp: '^.*<VirtualHost.*$'
        line: <VirtualHost *:8081>
        state: present
    - name: Install repositories for PHP
      apt:
        name: software-properties-common
        state: present
    - name: (Task 4) Install PHP with all with all modules
      apt: 
        name: ['php7.4', 'php7.4-common',
            'php7.4-opcache', 'php7.4-cli', 'php7.4-gd', 'php7.4-curl', 'php7.4-mysql', 'unzip', 'vim']
        state: present
    - name: Make a downloads directory at /etc to download the mysql package.
      file:
        path: /etc/downloads
        state: directory
    - name: Download mysql sources to the /etc/dowloads directory
      get_url: 
        url: https://repo.mysql.com//mysql-apt-config_0.8.13-1_all.deb 
        dest: /etc/downloads
    - name: Unpack the mysql-apt-config_0.8.13-1_all.deb.
      dpkg_selections:
        name: mysqlmysql-apt-config_0.8.13-1_all.deb
        selection: install
    - name: Install mysql-server
      apt:
        name: mysql-server
        state: present
    - name: Start mysql
      service:
        name: mysql
        enabled: yes
        state: started
    - name: Update the server
      apt:
        update_cache: yes
        force_apt_get: yes
        

    #- name: (Task ) Start apache2 server
      #service: 
        #name: apache2
        #state: started