- hosts: 172.31.25.198
  become: yes
  handlers:
    - name: restart Apache
      service: 
        name: httpd
        state: restarted
  tasks:
    - name: Install the Apache web server
      yum: 
        name: httpd 
        state: present
    - name: Ensure that Apache is started and enabled on system boot
      service: 
        name: httpd 
        state: started 
        enabled: yes
#    - name: Add EPEL repository
#      yum_repository:
#        name: epel
#        description: EPEL YUM repo
#        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
#    - name: Add public key of EPEL
#      rpm_key:
#        state: present
#        key: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
#    - name: Add Webtatic repository
#      yum:
#        name: https://mirror.webtatic.com/yum/el7/epel-release.rpm
#        state: present
    - name: Update the server
      yum:
        update_cache: yes
    - name: Install PHP 7 and some required packages
      yum:
        name: ['mariadb-server', 'mariadb', 'php', 'php-common', 'php-opcache', 'php-cli', 'php-gd', 'php-curl', 'php-mysqlnd', 'php-mbstring', 'unzip', 'curl', 'wget', 'bind-utils', 'telnet', 'git']
        state: present
#    - name: Download and extract the CodeIgniter archive to /var/www/html
#      unarchive:
#        src: https://github.com/bcit-ci/CodeIgniter/archive/3.1.5.zip
#        dest: /var/www/html
#        remote_src: yes
    
    - name: Deploy the swift application
      git:
        repo: https://github.com/abohmeed/swift
        dest: /var/www/html/CodeIgniter-3.1.5/
    - name: Change the files ownership to be owned by root
      file:
        path: /var/www/html
        owner: root
        #group: 
        recurse: yes 
    - name: Change the web home directory to point at /var/www/html/CodeIgniter-3.1.5
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^.*DocumentRoot "/var/www/html".*$'
        line: DocumentRoot "/var/www/html/CodeIgniter-3.1.5"
        state: present
      notify:
        - restart Apache
    - name: Ensure that mod_rewrite is enabled in Apache
      lineinfile:
        path: /etc/httpd/conf.modules.d/00-base.conf
        regexp: '^.*rewrite_module.*$'
        line: 'LoadModule rewrite_module modules/mod_rewrite.so'
        state: present
    - name: Copy htaccess to CodeIgniter
      copy:
        src: htaccess
        dest: /var/www/html/CodeIgniter-3.1.5/.htaccess
        owner: root
        #group: vagrant
    - name: Allow .htaccess file to be used
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        insertafter: '</Directory>'
        line: |
          <Directory "/var/www/html/CodeIgniter-3.1.5">
            AllowOverride all
          </Directory>
      notify:
        - restart Apache
    - name: Upload the database.php file 
      copy:
        src: database.php
        dest: /var/www/html/CodeIgniter-3.1.5/application/config/database.php
        owner: root
        #group: vagrant