- hosts: 172.17.0.3 
  become: no
  tasks:
    - name: Install required packages
      apt:
        name: ['git',
               'phpunit',
               'python3-apt',
               'python3-pip'
               'openjdk-11-jdk']
        state: present
    #- name: Install the Jenkins repo
      #apt_key:
        #url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
        #state: present
    #- name: Add Jenkins repository
      #apt_repository:
        #repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        #state: present
        #update_cache: yes
    #- name: Install Jenkins
      #apt:
        #name: jenkins
        #state: present
    - name: Start and enable the servcie
      service:
        name: jenkins
        state: started
        enabled: yes
    - name: Install Selenium testing framework
      pip: 
        name: selenium
        state: present
    - name: Update the server
      apt:
        update_cache: yes
        force_apt_get: yes