- hosts: 172.31.19.87 
  become: yes
  tasks:
    - name: Install required packages
      yum:
        name: ['git',
               'wget',
               'python3',
               'python3-pip',
               'java-11-openjdk']
        state: present
    - name: Install the Jenkins repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
    - name: Add Jenkins repository
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        state: present
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
    - name: Start and enable the servcie
      systemd:
        name: jenkins
        state: started
        enabled: yes
    - name: Install Selenium testing framework
      pip: 
        name: selenium
        state: present
    - name: Update the server
      yum:
        update_cache: yes
        